// What the playground says about a table (the side panel) and about a column (the small popover).
// Both are built from the model, so they state exactly what the diagram means, and both are plain
// HTML, so their text can be selected and copied.

import type { Model, ModelColumn, ModelTable, Relation } from "../src/index.ts";

type Child = Node | string | null | false | undefined;

function h<K extends keyof HTMLElementTagNameMap>(tag: K, cls: string | null, ...children: Child[]): HTMLElementTagNameMap[K] {
  const el = document.createElement(tag);
  if (cls) el.className = cls;
  for (const c of children) if (c !== null && c !== false && c !== undefined) el.append(c);
  return el;
}

/** Following a table name: the page decides what that does (open it in the panel, show it) */
export type OpenTable = (name: string) => void;
/** Picking a column from the panel */
export type PickColumn = (table: string, column: string) => void;

const keyOf = (c: ModelColumn, refs: Relation[]): "PK" | "UK" | "FK" | null => (c.pk ? "PK" : c.uk ? "UK" : refs.length ? "FK" : null);
const typeOf = (c: ModelColumn, t: ModelTable): string => c.type + (c.nullable && t.origin !== "audit" ? "?" : "");
const kindOf = (r: Relation): string => (r.kind === "physical" ? "foreign key" : "logical reference");

function link(name: string, open: OpenTable): HTMLButtonElement {
  const b = h("button", "d-link", name);
  b.type = "button";
  b.title = `Show ${name}`;
  b.addEventListener("click", () => open(name));
  return b;
}

const key = (k: string | null): Child => (k ? h("span", `d-key k-${k.toLowerCase()}`, k) : h("span", "d-key", ""));
const chip = (text: string): HTMLElement => h("span", "d-chip", text);
const code = (text: string): HTMLElement => h("code", null, text);

function section(title: string, ...items: Child[]): HTMLElement {
  return h("section", "d-section", h("h3", null, title), h("ul", null, ...items));
}

/** The side panel: everything about one table */
export function tableDetails(model: Model, name: string, open: OpenTable, pick: PickColumn): HTMLElement | null {
  const t = model.tables.find((x) => x.name === name);
  if (!t) return null;
  const outgoing = model.relations.filter((r) => r.child === name);
  const incoming = model.relations.filter((r) => r.parent === name);
  const tags = [t.origin === "external" && "EXTERNAL", t.origin === "audit" && "GENERATED", t.audit && t.audit.method.toUpperCase()].filter(
    (x): x is string => typeof x === "string",
  );
  const plural = (n: number, word: string) => `${n} ${word}${n === 1 ? "" : "s"}`;

  const columns = t.columns.map((c) => {
    const refs = outgoing.filter((r) => r.childColumn === c.name);
    const facts: string[] = [];
    if (c.enumValues) facts.push(`enum ${c.enumValues.join(", ")}`);
    if (c.enc) facts.push("encrypted");
    if (c.index) facts.push(c.index.name ? `index ${c.index.name}` : "index");
    if (c.uk && c.ukName) facts.push(`unique ${c.ukName}`);
    for (const r of refs) facts.push(`${r.kind === "physical" ? "->" : "~>"} ${r.parent}.${r.parentColumn}`);
    const nameButton = h("button", "d-col-name", c.name);
    nameButton.type = "button";
    nameButton.title = "Show this column on the diagram";
    nameButton.addEventListener("click", () => pick(t.name, c.name));
    return h(
      "li",
      "d-col",
      key(keyOf(c, refs)),
      nameButton,
      h("span", "d-type", typeOf(c, t)),
      c.description ? h("span", "d-col-desc", c.description) : null,
      facts.length ? h("span", "d-col-facts", ...facts.map(chip)) : null,
    );
  });

  const audit: Child[] = [];
  if (t.audit) {
    audit.push(
      h("li", "d-note", `Audited with ${t.audit.method} on `, ...t.audit.columns.flatMap((c, i) => [i ? ", " : "", code(c)]), "."),
      h("li", "d-note", "Generated tables: ", link("revinfo", open), ", ", link(`${t.name}_aud`, open)),
    );
  } else if (t.origin === "audit") {
    const base = t.name.endsWith("_aud") ? t.name.slice(0, -4) : null;
    audit.push(
      base
        ? h("li", "d-note", "Generated by the audit of ", link(base, open), ": one row per revision of each change.")
        : h("li", "d-note", "One row per revision, shared by every audited table."),
    );
  }

  return h(
    "div",
    "d-table",
    h(
      "header",
      "d-head",
      h("h2", "d-name", t.name),
      tags.length ? h("span", "d-tags", ...tags.map(chip)) : null,
      t.description ? h("p", "d-desc", t.description) : null,
      h("p", "d-meta", `${plural(t.columns.length, "column")}, ${plural(outgoing.length, "reference")}, referenced by ${incoming.length}`),
    ),
    section("Columns", ...columns),
    t.constraints.length
      ? section(
          "Constraints",
          ...t.constraints.map((k) => h("li", "d-con", chip(k.kind === "unique" ? "UNIQUE" : "INDEX"), code(k.name ?? "unnamed"), ` (${k.columns.join(", ")})`)),
        )
      : null,
    outgoing.length
      ? section(
          "References",
          ...outgoing.map((r) =>
            h(
              "li",
              "d-rel",
              code(r.childColumn),
              " → ",
              link(r.parent, open),
              code(`.${r.parentColumn}`),
              h("span", "d-rel-meta", `${kindOf(r)}, ${r.one ? "one-to-one" : "many-to-one"}${r.optional ? ", optional" : ""}`),
            ),
          ),
        )
      : null,
    incoming.length
      ? section(
          "Referenced by",
          ...incoming.map((r) =>
            h(
              "li",
              "d-rel",
              link(r.child, open),
              code(`.${r.childColumn}`),
              " → ",
              code(r.parentColumn),
              h("span", "d-rel-meta", `${kindOf(r)}, ${r.one ? "one-to-one" : "one-to-many"}`),
            ),
          ),
        )
      : null,
    audit.length ? section("Audit", ...audit) : null,
  );
}

/** The popover: one column, in a few lines */
export function columnDetails(model: Model, table: string, column: string, open: OpenTable): HTMLElement | null {
  const t = model.tables.find((x) => x.name === table);
  const c = t?.columns.find((x) => x.name === column);
  if (!t || !c) return null;
  const outgoing = model.relations.filter((r) => r.child === table && r.childColumn === column);
  const incoming = model.relations.filter((r) => r.parent === table && r.parentColumn === column);
  const facts: [string, Child[]][] = [["Table", [link(t.name, open)]], ["Null", [c.nullable ? "allowed" : "not null"]]];
  if (c.enumValues) facts.push(["Values", [c.enumValues.join(", ")]]);
  if (c.enc) facts.push(["Stored", ["encrypted"]]);
  if (c.index) facts.push(["Index", [c.index.name ?? "yes"]]);
  if (c.uk) facts.push(["Unique", [c.ukName ?? "yes"]]);
  for (const r of outgoing) facts.push(["References", [link(r.parent, open), `.${r.parentColumn}, ${kindOf(r)}`]]);
  if (incoming.length)
    facts.push(["Referenced by", incoming.flatMap((r, i) => [i ? ", " : "", link(r.child, open), `.${r.childColumn}`])]);
  return h(
    "div",
    "d-pop",
    h("div", "d-pop-head", key(keyOf(c, outgoing)), h("span", "d-pop-name", c.name), h("span", "d-type", typeOf(c, t))),
    c.description ? h("p", "d-desc", c.description) : null,
    h("dl", "d-facts", ...facts.flatMap(([k, v]) => [h("dt", null, k), h("dd", null, ...v)])),
  );
}
