import { readFileSync, readdirSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { SQL_DIALECTS, type SqlDialect, toSql } from "./ddl.ts";
import { compile, diff, diffMarkdown, fromSql } from "./index.ts";

const modelOf = (src: string) => {
  const r = compile(src);
  expect(r.diagnostics.filter((d) => d.severity === "error")).toEqual([]);
  return r.model!;
};

const SHOP = `service accounts "Accounts service" {
  table users "People who sign in" {
    id     bigint        pk
    email  varchar(255)  uk  "Login address"
  }
}

service ordering {
  table orders {
    id       bigint   pk
    user_id  bigint   -> users  index
    status   varchar  enum(PENDING, PAID)  index as ix_orders_status
    note     text?    enc
  }
}
`;

describe("toSql", () => {
  it("writes PostgreSQL: a schema per service, checks, comments, indexes and foreign keys at the end", () => {
    const r = toSql(modelOf(SHOP), { dialect: "postgres" });
    expect(r.notes).toEqual([]);
    expect(r.sql).toBe(`-- Generated by resin for PostgreSQL

CREATE SCHEMA accounts;
CREATE SCHEMA ordering;

CREATE TABLE accounts.users (
  id     bigint        NOT NULL,
  email  varchar(255)  NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (email)
);
COMMENT ON TABLE accounts.users IS 'People who sign in';
COMMENT ON COLUMN accounts.users.email IS 'Login address';

CREATE TABLE ordering.orders (
  id       bigint   NOT NULL,
  user_id  bigint   NOT NULL,
  status   varchar  NOT NULL CHECK (status IN ('PENDING', 'PAID')),
  note     text,  -- encrypted
  PRIMARY KEY (id)
);
CREATE INDEX ON ordering.orders (user_id);
CREATE INDEX ix_orders_status ON ordering.orders (status);

ALTER TABLE ordering.orders ADD FOREIGN KEY (user_id) REFERENCES accounts.users (id);
`);
  });

  it("writes one service for its own database, leaving foreign keys into other services as comments", () => {
    const r = toSql(modelOf(SHOP), { dialect: "postgres", service: "ordering" });
    expect(r.notes).toEqual(["orders.user_id -> accounts.users.id: in another service, so no FOREIGN KEY"]);
    expect(r.sql).toBe(`-- Generated by resin for PostgreSQL, service ordering

CREATE TABLE orders (
  id       bigint   NOT NULL,
  user_id  bigint   NOT NULL,  -- -> accounts.users.id, in another service: no FOREIGN KEY
  status   varchar  NOT NULL CHECK (status IN ('PENDING', 'PAID')),
  note     text,  -- encrypted
  PRIMARY KEY (id)
);
CREATE INDEX ON orders (user_id);
CREATE INDEX ix_orders_status ON orders (status);
`);
    expect(() => toSql(modelOf(SHOP), { dialect: "postgres", service: "billing" })).toThrow("there is no service `billing`");
  });

  it("writes MySQL: backticks for reserved words, inline indexes and comments, the enum type, logical references as comments", () => {
    const r = toSql(
      modelOf(`table order "Customer orders" {
  id       bigint  pk
  user_id  bigint  ~> users  index
  kind     enum    enum(ONLINE, STORE)  "Where it was placed"
}

table users {
  id  bigint  pk
}
`),
      { dialect: "mysql" },
    );
    expect(r.notes).toEqual([]);
    expect(r.sql).toBe(`-- Generated by resin for MySQL

CREATE TABLE \`order\` (
  id       bigint                   NOT NULL,
  user_id  bigint                   NOT NULL,  -- ~> users.id
  kind     enum('ONLINE', 'STORE')  NOT NULL COMMENT 'Where it was placed',
  PRIMARY KEY (id),
  INDEX (user_id)
) COMMENT = 'Customer orders';

CREATE TABLE users (
  id  bigint  NOT NULL,
  PRIMARY KEY (id)
);
`);
  });

  it("writes SQLite: foreign keys inside the table, made-up index names, descriptions as comments", () => {
    const r = toSql(
      modelOf(`table users "People" {
  id  integer  pk
}

table orders {
  id       integer  pk
  user_id  integer  -> users  index  "Buyer"
}
`),
      { dialect: "sqlite" },
    );
    expect(r.notes).toEqual(["the index on orders (user_id) has no name, which SQLite needs: named ix_orders_user_id"]);
    expect(r.sql).toBe(`-- Generated by resin for SQLite

-- People
CREATE TABLE users (
  id  integer  NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE orders (
  id       integer  NOT NULL,
  user_id  integer  NOT NULL,  -- Buyer
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users (id)
);
CREATE INDEX ix_orders_user_id ON orders (user_id);
`);
  });

  it("writes SQL Server: brackets, MS_Description, named constraints and composite keys", () => {
    const r = toSql(
      modelOf(`table users "People" {
  id    bigint        pk
  name  nvarchar(80)  "Full name"
}

table \`group\` {
  user_id  bigint       pk
  team_id  bigint       pk
  role     varchar(20)
  unique(team_id, role) as uk_team_role
  index(role, user_id) as ix_role_user
}
`),
      { dialect: "sqlserver" },
    );
    expect(r.notes).toEqual([]);
    expect(r.sql).toBe(`-- Generated by resin for SQL Server

CREATE TABLE dbo.users (
  id    bigint        NOT NULL,
  name  nvarchar(80)  NOT NULL,
  PRIMARY KEY (id)
);
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'People', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'users';
EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'Full name', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'users', @level2type = N'COLUMN', @level2name = N'name';

CREATE TABLE dbo.[group] (
  user_id  bigint       NOT NULL,
  team_id  bigint       NOT NULL,
  role     varchar(20)  NOT NULL,
  PRIMARY KEY (user_id, team_id),
  CONSTRAINT uk_team_role UNIQUE (team_id, role)
);
CREATE INDEX ix_role_user ON dbo.[group] (role, user_id);
`);
  });

  it("writes composite and named foreign keys, logical composite references as comments, and doubles quotes in strings", () => {
    const r = toSql(
      modelOf(`table shops {
  tenant_id  bigint  pk
  id         bigint  pk
}

table items "It's an item" {
  id         bigint  pk
  tenant_id  bigint
  shop_id    bigint
  owner_id   bigint
  foreign(tenant_id, shop_id) -> shops(tenant_id, id) as fk_item_shop
  foreign(tenant_id, owner_id) ~> shops(tenant_id, id)
}
`),
      { dialect: "postgres" },
    );
    expect(r.sql).toBe(`-- Generated by resin for PostgreSQL

CREATE TABLE shops (
  tenant_id  bigint  NOT NULL,
  id         bigint  NOT NULL,
  PRIMARY KEY (tenant_id, id)
);

CREATE TABLE items (
  id         bigint  NOT NULL,
  tenant_id  bigint  NOT NULL,
  shop_id    bigint  NOT NULL,
  owner_id   bigint  NOT NULL,
  PRIMARY KEY (id)
  -- (tenant_id, owner_id) ~> shops (tenant_id, id)
);
COMMENT ON TABLE items IS 'It''s an item';

ALTER TABLE items ADD CONSTRAINT fk_item_shop FOREIGN KEY (tenant_id, shop_id) REFERENCES shops (tenant_id, id);
`);
  });

  it("creates the audit tables, a PostgreSQL enum type once, and notes Oracle's schemas", () => {
    const pg = toSql(
      modelOf(`table orders {
  id      bigint        pk
  status  order_status  enum(NEW, PAID)
  prior   order_status? enum(NEW, PAID)
} audit envers(status)
`),
      { dialect: "postgres" },
    );
    expect(pg.sql).toBe(`-- Generated by resin for PostgreSQL

CREATE TYPE order_status AS ENUM ('NEW', 'PAID');

CREATE TABLE orders (
  id      bigint        NOT NULL,
  status  order_status  NOT NULL,
  prior   order_status,
  PRIMARY KEY (id)
);

CREATE TABLE revinfo (
  rev       int     NOT NULL,
  revtstmp  bigint  NOT NULL,
  PRIMARY KEY (rev)
);

CREATE TABLE orders_aud (
  id       bigint        NOT NULL,
  rev      int           NOT NULL,  -- ~> revinfo.rev
  revtype  tinyint       NOT NULL,
  status   order_status,
  PRIMARY KEY (id, rev)
);
`);
    const oracle = toSql(modelOf(SHOP), { dialect: "oracle" });
    expect(oracle.notes).toEqual([
      "services are written as schemas, which Oracle makes as users: CREATE SCHEMA is left out, so create the users accounts and ordering first",
      "the index on ordering.orders (user_id) has no name, which Oracle needs: named ix_orders_user_id",
    ]);
    expect(oracle.sql).not.toContain("CREATE SCHEMA");
  });
});

// resin → SQL → resin gives the same document back, apart from what SQL cannot hold (SPEC §12.4).
// The SQL golden documents were imported from each dialect, so each goes back to its own.
describe("round trip through SQL", () => {
  const goldens = readdirSync(new URL("../examples/sql/", import.meta.url))
    .filter((f) => f.endsWith(".erd"))
    .map((f) => [f.replace(".erd", "") as SqlDialect, readFileSync(new URL(`../examples/sql/${f}`, import.meta.url), "utf8")] as const);

  it.each(goldens)("examples/sql/%s.erd", (dialect, text) => {
    const before = modelOf(text);
    const sql = toSql(before, { dialect }).sql;
    const after = modelOf(fromSql(sql).source);
    expect(diffMarkdown(diff(before, after).changes)).toBe("No changes to the schema.\n");
  });

  // Everything toSql writes is something fromSql reads: an import of it notes nothing it skipped
  const examples = readdirSync(new URL("../examples/", import.meta.url)).filter((f) => f.endsWith(".erd"));
  const cases = examples.flatMap((f) => SQL_DIALECTS.map((d) => [f, d] as const));
  it.each(cases)("examples/%s in %s imports without a note", (file, dialect) => {
    const sql = toSql(modelOf(readFileSync(new URL(`../examples/${file}`, import.meta.url), "utf8")), { dialect }).sql;
    expect(fromSql(sql).notes).toEqual([]);
  });
});
