// Checked syntax tree → model. Every output (Mermaid, SVG) reads the model and nothing else.
//
// Why a separate step: resolving references, deciding one-to-one versus one-to-many, whether a parent
// is optional, expanding audit tables — if every output derived these on its own, outputs would drift
// apart. They are derived here once, and their tests live here too. Source positions are dropped:
// the model only says what to draw.

import { type Column, type Document, type Table, typeText } from "./ast.ts";
import { AUDIT_SUFFIX, REVINFO, auditedColumns, resolveRef } from "./checker.ts";

export type TableOrigin = "table" | "external" | "audit";

export interface Model {
  /** Document order (external tables included), followed by expanded audit tables (revinfo, *_aud) */
  tables: ModelTable[];
  /** In document order of the child table and column, followed by audit relations */
  relations: Relation[];
}

export interface ModelTable {
  name: string;
  description: string | null;
  /** table = declared in the document, external = lives outside it, audit = generated by `audit` */
  origin: TableOrigin;
  columns: ModelColumn[];
  constraints: ModelConstraint[];
  /** The audit attached to this table, for outputs that fold audit tables away */
  audit: { method: string; columns: string[] } | null;
}

export interface ModelColumn {
  name: string;
  /** With its arguments, as written: `varchar(32)` */
  type: string;
  nullable: boolean;
  pk: boolean;
  uk: boolean;
  ukName: string | null;
  enc: boolean;
  enumValues: string[] | null;
  index: { name: string | null } | null;
  description: string | null;
  ref: { table: string; column: string; kind: "physical" | "logical" } | null;
}

export interface ModelConstraint {
  kind: "unique" | "index";
  name: string | null;
  columns: string[];
}

export interface Relation {
  parent: string;
  parentColumn: string;
  child: string;
  childColumn: string;
  kind: "physical" | "logical";
  /** One-to-one: the referencing column is `uk` or the table's only primary key */
  one: boolean;
  /** The parent may be absent: the referencing column is nullable */
  optional: boolean;
  origin: "table" | "audit";
}

const plain = (name: string, type: string, extra: Partial<ModelColumn> = {}): ModelColumn => ({
  name,
  type,
  nullable: false,
  pk: false,
  uk: false,
  ukName: null,
  enc: false,
  enumValues: null,
  index: null,
  description: null,
  ref: null,
  ...extra,
});

export function lower(doc: Document): Model {
  const tables: ModelTable[] = [];
  const relations: Relation[] = [];

  for (const t of doc.tables) {
    const pkCount = t.columns.filter((c) => c.pk).length;
    tables.push({
      name: t.name.text,
      description: t.description,
      origin: t.external ? "external" : "table",
      columns: t.columns.map((c) => column(doc, c)),
      constraints: t.constraints.map((k) => ({ kind: k.kind, name: k.name?.text ?? null, columns: k.columns.map((i) => i.text) })),
      audit: t.audit ? { method: t.audit.method.text, columns: auditedColumns(t).map((c) => c.name.text) } : null,
    });
    for (const c of t.columns) {
      const target = resolveRef(doc, c);
      if (!target) continue;
      relations.push({
        parent: target.table.name.text,
        parentColumn: target.column.name.text,
        child: t.name.text,
        childColumn: c.name.text,
        kind: c.ref!.kind,
        one: c.uk !== null || (c.pk && pkCount === 1),
        optional: c.nullable,
        origin: "table",
      });
    }
  }

  const audited = doc.tables.filter((t) => t.audit && !t.external);
  if (audited.length > 0) {
    tables.push({
      name: REVINFO,
      description: null,
      origin: "audit",
      columns: [plain("rev", "int", { pk: true }), plain("revtstmp", "bigint")],
      constraints: [],
      audit: null,
    });
    for (const t of audited) tables.push(envers(t));
    for (const t of audited)
      relations.push({
        parent: REVINFO,
        parentColumn: "rev",
        child: t.name.text + AUDIT_SUFFIX,
        childColumn: "rev",
        kind: "logical",
        one: false,
        optional: false,
        origin: "audit",
      });
  }
  return { tables, relations };
}

function column(doc: Document, c: Column): ModelColumn {
  const target = resolveRef(doc, c);
  return {
    name: c.name.text,
    type: typeText(c.type),
    nullable: c.nullable,
    pk: c.pk,
    uk: c.uk !== null,
    ukName: c.uk?.name?.text ?? null,
    enc: c.enc,
    enumValues: c.enumValues?.map((v) => v.text) ?? null,
    index: c.index ? { name: c.index.name?.text ?? null } : null,
    description: c.description,
    ref: target && c.ref ? { table: target.table.name.text, column: target.column.name.text, kind: c.ref.kind } : null,
  };
}

/** A Hibernate Envers audit table: the primary key, rev, revtype and the audited columns.
 *  Audited columns are nullable: Envers leaves everything but the key empty in delete revisions */
function envers(t: Table): ModelTable {
  return {
    name: t.name.text + AUDIT_SUFFIX,
    description: null,
    origin: "audit",
    columns: [
      ...t.columns.filter((c) => c.pk).map((c) => plain(c.name.text, typeText(c.type), { pk: true })),
      plain("rev", "int", { pk: true, ref: { table: REVINFO, column: "rev", kind: "logical" } }),
      plain("revtype", "tinyint"),
      ...auditedColumns(t).map((c) => plain(c.name.text, typeText(c.type), { nullable: true })),
    ],
    constraints: [],
    audit: null,
  };
}
