// Checked syntax tree → model. Every output (the SVG, the JSON of `--model`) reads the model and nothing else.
//
// Why a separate step: resolving references, deciding one-to-one versus one-to-many, whether a parent
// is optional, expanding audit tables — if every output derived these on its own, outputs would drift
// apart. They are derived here once, and their tests live here too. Source positions are dropped:
// the model only says what to draw.

import { type Column, type Document, type Table, tableId, typeText } from "./ast.ts";
import { AUDIT_SUFFIX, REVINFO, auditedColumns } from "./checker.ts";
import { Resolution } from "./resolution.ts";
import type { Change } from "./diff.ts";

export type TableOrigin = "table" | "external" | "audit";

export interface Model {
  /** Document order (external tables included), followed by expanded audit tables (revinfo, *_aud) */
  tables: ModelTable[];
  /** In document order of the child table and column, followed by audit relations */
  relations: Relation[];
  /** The services that own the tables, each drawn as an area. In document order */
  services: ModelService[];
}

export interface ModelService {
  name: string;
  description: string | null;
}

export interface ModelTable {
  name: string;
  label?: string;
  description: string | null;
  /** table = declared in the document, external = lives outside it, audit = generated by `audit` */
  origin: TableOrigin;
  columns: ModelColumn[];
  constraints: ModelConstraint[];
  /** The audit attached to this table, for outputs that fold audit tables away */
  audit: { method: string; columns: string[] } | null;
  /** The service the table belongs to, or null */
  service: string | null;
  foreignKeys?: { columns: string[]; target: string; targetColumns: string[]; kind: "physical" | "logical"; name: string | null }[];
  /** Set by `diff` only: how the table changed */
  change?: Change;
}

export interface ModelColumn {
  name: string;
  /** With its arguments, as written: `varchar(32)` */
  type: string;
  nullable: boolean;
  pk: boolean;
  uk: boolean;
  ukName: string | null;
  enc: boolean;
  enumValues: string[] | null;
  index: { name: string | null } | null;
  description: string | null;
  ref: { table: string; column: string; kind: "physical" | "logical" } | null;
  /** Set by `diff` only: how the column changed */
  change?: Change;
}

export interface ModelConstraint {
  kind: "unique" | "index";
  name: string | null;
  columns: string[];
}

export interface Relation {
  parent: string;
  parentColumn: string;
  child: string;
  childColumn: string;
  parentColumns?: string[];
  childColumns?: string[];
  constraint?: string | null;
  kind: "physical" | "logical";
  /** One-to-one: the referencing column is `uk` or the table's only primary key */
  one: boolean;
  /** The parent may be absent: the referencing column is nullable */
  optional: boolean;
  origin: "table" | "audit";
  /** Set by `diff` only: how the relation changed */
  change?: Change;
}

const plain = (name: string, type: string, extra: Partial<ModelColumn> = {}): ModelColumn => ({
  name,
  type,
  nullable: false,
  pk: false,
  uk: false,
  ukName: null,
  enc: false,
  enumValues: null,
  index: null,
  description: null,
  ref: null,
  ...extra,
});

export function lower(doc: Document, resolution = new Resolution(doc)): Model {
  const tables: ModelTable[] = [];
  const relations: Relation[] = [];

  for (const t of doc.tables) {
    const pkCount = t.columns.filter((c) => c.pk).length;
    tables.push({
      name: tableId(t),
      ...(t.service || t.name.text.includes(".") ? { label: t.name.text } : {}),
      description: t.description,
      origin: t.external ? "external" : "table",
      columns: t.columns.map((c) => column(resolution, c)),
      constraints: t.constraints.map((k) => ({ kind: k.kind, name: k.name?.text ?? null, columns: k.columns.map((i) => i.text) })),
      audit: t.audit ? { method: t.audit.method.text, columns: auditedColumns(t).map((c) => c.name.text) } : null,
      service: t.service?.text ?? null,
      ...(t.foreignKeys.length ? { foreignKeys: t.foreignKeys.map(fk => ({ columns: fk.columns.map(c => c.text), target: tableId(resolution.table(fk.table.text, t, fk.service?.text)!), targetColumns: fk.targetColumns.map(c => c.text), kind: fk.kind, name: fk.name?.text ?? null })) } : {}),
    });
    for (const c of t.columns) {
      const target = resolution.ref(c);
      if (!target) continue;
      relations.push({
        parent: tableId(target.table),
        parentColumn: target.column.name.text,
        child: tableId(t),
        childColumn: c.name.text,
        kind: c.ref!.kind,
        one: c.uk !== null || (c.pk && pkCount === 1),
        optional: c.nullable,
        origin: "table",
      });
    }
    for (const fk of t.foreignKeys) {
      const target = resolution.table(fk.table.text, t, fk.service?.text)!;
      const cols = fk.columns.map(c => c.text);
      const pk = t.columns.filter(c => c.pk).map(c => c.name.text);
      const same = (other: string[]) => other.length === cols.length && cols.every(c => other.includes(c));
      relations.push({ parent: tableId(target), child: tableId(t), parentColumn: fk.targetColumns[0].text, childColumn: cols[0],
        parentColumns: fk.targetColumns.map(c => c.text), childColumns: cols, constraint: fk.name?.text ?? null,
        kind: fk.kind, one: same(pk) || t.constraints.some(k => k.kind === "unique" && same(k.columns.map(c => c.text))),
        optional: t.columns.some(c => cols.includes(c.name.text) && c.nullable), origin: "table" });
    }
  }

  const audited = doc.tables.filter((t) => t.audit && !t.external);
  if (audited.length > 0) {
    tables.push({
      name: REVINFO,
      description: null,
      origin: "audit",
      columns: [plain("rev", "int", { pk: true }), plain("revtstmp", "bigint")],
      constraints: [],
      audit: null,
      service: null,
    });
    for (const t of audited) tables.push(envers(t));
    for (const t of audited)
      relations.push({
        parent: REVINFO,
        parentColumn: "rev",
        child: tableId(t, t.name.text + AUDIT_SUFFIX),
        childColumn: "rev",
        kind: "logical",
        one: false,
        optional: false,
        origin: "audit",
      });
  }
  // A service declared twice is an error, so names are unique here
  return { tables, relations, services: doc.services.map((s) => ({ name: s.name.text, description: s.description })) };
}

function column(resolution: Resolution, c: Column): ModelColumn {
  const target = resolution.ref(c);
  return {
    name: c.name.text,
    type: typeText(c.type),
    nullable: c.nullable,
    pk: c.pk,
    uk: c.uk !== null,
    ukName: c.uk?.name?.text ?? null,
    enc: c.enc,
    enumValues: c.enumValues?.map((v) => v.text) ?? null,
    index: c.index ? { name: c.index.name?.text ?? null } : null,
    description: c.description,
    ref: target && c.ref ? { table: tableId(target.table), column: target.column.name.text, kind: c.ref.kind } : null,
  };
}

/** A Hibernate Envers audit table: the primary key, rev, revtype and the audited columns.
 *  Audited columns are nullable: Envers leaves everything but the key empty in delete revisions */
function envers(t: Table): ModelTable {
  return {
    name: tableId(t, t.name.text + AUDIT_SUFFIX),
    ...(t.service || t.name.text.includes(".") ? { label: t.name.text + AUDIT_SUFFIX } : {}),
    description: null,
    origin: "audit",
    columns: [
      ...t.columns.filter((c) => c.pk).map((c) => plain(c.name.text, typeText(c.type), { pk: true })),
      plain("rev", "int", { pk: true, ref: { table: REVINFO, column: "rev", kind: "logical" } }),
      plain("revtype", "tinyint"),
      ...auditedColumns(t).map((c) => plain(c.name.text, typeText(c.type), { nullable: true })),
    ],
    constraints: [],
    audit: null,
    // An audit table sits with the table it audits
    service: t.service?.text ?? null,
  };
}

/** The part of a model within `steps` references of one table: the tables that many hops away and
 *  every relation among them. One step is one hop: a table's parents and children. Columns keep
 *  their references to tables left out, so they still read as foreign keys. Audit relations do not
 *  count as hops */
export function neighbors(model: Model, table: string, steps: number): Model {
  const keep = new Set([table]);
  for (let s = 0; s < steps; s++) {
    const from = new Set(keep);
    for (const r of model.relations)
      if (r.origin === "table" && (from.has(r.parent) || from.has(r.child))) {
        keep.add(r.parent);
        keep.add(r.child);
      }
  }
  const tables = model.tables.filter((t) => keep.has(t.name));
  return {
    tables,
    relations: model.relations.filter((r) => keep.has(r.parent) && keep.has(r.child)),
    // Every service stays: a service's place among them picks its color, which a part should not change
    services: model.services,
  };
}
