// One SQL statement (a list of tokens from sql-lexer.ts) → the facts it states about a schema, for
// the SQL importer (sql.ts).
//
// This is not a SQL parser. It reads the handful of statements that define a schema (CREATE TABLE,
// ALTER TABLE ... ADD, CREATE INDEX, COMMENT ON, CREATE TYPE ... AS ENUM, SQL Server's
// sp_addextendedproperty) and recognizes the rest only far enough to skip it. Inside a statement it
// is lenient on purpose: an attribute it does not know (a storage clause, a vendor option) is
// skipped word by word rather than failing the column, because dumps are full of them and none of
// them changes what a diagram shows. What it must not do is misread one: the clauses that contain
// words with a meaning of their own (`ON DELETE SET NULL`, `GENERATED BY DEFAULT ON NULL`) are
// therefore consumed as a whole.
//
// A table body is split at its top-level commas first, so one unreadable element costs only itself.

import type { SqlToken } from "./sql-lexer.ts";

/** A possibly qualified name (`public.orders`, `[dbo].[Users]`); the last part is the object */
export interface SqlName {
  parts: string[];
  line: number;
  col: number;
}

export const objectName = (n: SqlName): string => n.parts[n.parts.length - 1];
export const schemaName = (n: SqlName): string | null => (n.parts.length > 1 ? n.parts[n.parts.length - 2] : null);

export interface SqlType {
  /** Lowercase, normalized to one resin identifier: `character varying` → `varchar` */
  name: string;
  args: number[] | null;
  /** The values of MySQL's `enum('a', 'b')` */
  values: string[] | null;
}

export interface SqlRef {
  table: SqlName;
  /** null when the reference names no column: it points at the primary key */
  columns: string[] | null;
}

export interface SqlColumn {
  name: string;
  type: SqlType;
  notNull: boolean;
  pk: boolean;
  unique: { name: string | null } | null;
  ref: SqlRef | null;
  /** From a value list check: `CHECK (status IN ('A', 'B'))` */
  checkValues: string[] | null;
  comment: string | null;
  line: number;
  col: number;
}

export type IndexItem = { column: string } | { expression: string };

export type SqlConstraint =
  | { kind: "pk"; columns: string[] }
  /** UNIQUE constraints and indexes alike: a unique constraint is a unique index with a name */
  | { kind: "index"; name: string | null; unique: boolean; items: IndexItem[]; where: string | null }
  | { kind: "fk"; columns: string[]; ref: SqlRef }
  | { kind: "check"; column: string; values: string[] };

export interface SqlTable {
  name: SqlName;
  columns: SqlColumn[];
  constraints: { constraint: SqlConstraint; line: number; col: number }[];
  comment: string | null;
  /** Elements of the body that could not be read */
  unreadable: { text: string; line: number; col: number }[];
}

export type AlterAction =
  | { kind: "constraint"; constraint: SqlConstraint; line: number; col: number }
  | { kind: "column"; column: SqlColumn }
  | { kind: "null"; column: string; notNull: boolean };

export type SqlStatement =
  | { kind: "table"; table: SqlTable }
  | { kind: "alter"; table: SqlName; actions: AlterAction[] }
  | { kind: "index"; table: SqlName; index: Extract<SqlConstraint, { kind: "index" }> }
  | { kind: "comment"; on: "table" | "column"; name: SqlName; text: string | null }
  | { kind: "enum"; name: SqlName; values: string[] }
  | { kind: "enum-value"; name: SqlName; value: string }
  /** mysqldump creates a placeholder table for every view and drops it before the view */
  | { kind: "drop"; names: SqlName[] }
  /** A schema object resin does not draw (`view`, `trigger`, ...), or null for statements that define
   *  none: session settings, data, privileges, sequences */
  | { kind: "skip"; object: string | null; name: string | null }
  /** A CREATE TABLE without a column list (`AS SELECT`, `LIKE`) or one that could not be read */
  | { kind: "unreadable"; what: string };

// ---- a cursor over a token list ----

class Cursor {
  readonly tokens: SqlToken[];
  pos = 0;

  constructor(tokens: SqlToken[]) {
    this.tokens = tokens;
  }

  peek(k = 0): SqlToken | undefined {
    return this.tokens[this.pos + k];
  }
  get done(): boolean {
    return this.pos >= this.tokens.length;
  }
  next(): SqlToken {
    return this.tokens[this.pos++];
  }
  word(w: string, k = 0): boolean {
    const t = this.peek(k);
    return t !== undefined && t.kind === "word" && t.upper === w;
  }
  /** Consume these words, in this order, or nothing */
  eat(...ws: string[]): boolean {
    if (!ws.every((w, k) => this.word(w, k))) return false;
    this.pos += ws.length;
    return true;
  }
  /** Consume any number of these words, in any order */
  eatAny(...ws: string[]): void {
    while (ws.some((w) => this.word(w))) this.pos++;
  }
  punct(p: string, k = 0): boolean {
    const t = this.peek(k);
    return t !== undefined && t.kind === "punct" && t.value === p;
  }
  isName(k = 0): boolean {
    const t = this.peek(k);
    return t !== undefined && (t.kind === "word" || t.kind === "quoted");
  }
  /** The tokens inside a balanced (...) group, consumed; null when not at `(` */
  group(): SqlToken[] | null {
    if (!this.punct("(")) return null;
    const start = this.pos;
    let depth = 0;
    while (!this.done) {
      const t = this.next();
      if (t.kind !== "punct") continue;
      if (t.value === "(") depth++;
      else if (t.value === ")" && --depth === 0) return this.tokens.slice(start + 1, this.pos - 1);
    }
    return this.tokens.slice(start + 1);
  }
  skipGroup(): void {
    this.group();
  }
  /** `a`, `a.b`, `a.b.c`, each part bare or quoted */
  name(): SqlName | null {
    if (!this.isName()) return null;
    const first = this.next();
    const parts = [first.value];
    while (this.punct(".") && this.isName(1)) {
      this.pos++;
      parts.push(this.next().value);
    }
    return { parts, line: first.line, col: first.col };
  }
  rest(): SqlToken[] {
    const out = this.tokens.slice(this.pos);
    this.pos = this.tokens.length;
    return out;
  }
}

/** Split at commas outside parentheses and brackets */
export function splitTop(tokens: readonly SqlToken[]): SqlToken[][] {
  const out: SqlToken[][] = [];
  let part: SqlToken[] = [];
  let depth = 0;
  for (const t of tokens) {
    if (t.kind === "punct") {
      if (t.value === "(" || t.value === "[") depth++;
      else if (t.value === ")" || t.value === "]") depth--;
      else if (t.value === "," && depth === 0) {
        out.push(part);
        part = [];
        continue;
      }
    }
    part.push(t);
  }
  if (part.length) out.push(part);
  return out.filter((p) => p.length > 0);
}

/** The source text a run of tokens came from, on one line and cut short */
export function snippet(text: string, tokens: readonly SqlToken[], max = 80): string {
  if (tokens.length === 0) return "";
  const s = text.slice(tokens[0].start, tokens[tokens.length - 1].end).replace(/\s+/g, " ").trim();
  return s.length > max ? `${s.slice(0, max - 3)}...` : s;
}

// ---- statements ----

/** Objects a CREATE can define that a diagram of tables does not show, but a reader may look for */
const OBJECTS: [string, string][] = [
  ["VIEW", "view"],
  ["TRIGGER", "trigger"],
  ["FUNCTION", "function"],
  ["PROCEDURE", "procedure"],
];

export function parseStatement(tokens: SqlToken[], text: string): SqlStatement {
  const c = new Cursor(tokens);
  if (c.eat("CREATE")) {
    c.eat("OR", "REPLACE");
    c.eat("OR", "ALTER");
    c.eatAny("GLOBAL", "LOCAL", "TEMPORARY", "TEMP", "UNLOGGED", "TRANSIENT", "VOLATILE");
    if (c.eat("TABLE")) return createTable(c, text);
    const start = c.pos;
    const unique = c.eat("UNIQUE");
    c.eatAny("CLUSTERED", "NONCLUSTERED", "FULLTEXT", "SPATIAL", "BITMAP");
    if (c.eat("INDEX")) return createIndex(c, text, unique);
    c.pos = start;
    if (c.eat("TYPE")) {
      const name = c.name();
      if (name && c.eat("AS", "ENUM")) return { kind: "enum", name, values: strings(c.group() ?? []) };
      return { kind: "skip", object: null, name: null };
    }
    // MySQL puts options first (`CREATE ALGORITHM=UNDEFINED DEFINER=... VIEW v`): look a little ahead
    for (let k = 0; k < 16 && !c.done; k++, c.pos++) {
      const materialized = c.word("MATERIALIZED") && c.word("VIEW", 1);
      const object = OBJECTS.find(([w]) => c.word(w));
      if (!materialized && !object) continue;
      c.pos += materialized ? 2 : 1;
      c.eat("IF", "NOT", "EXISTS");
      const name = c.name();
      return { kind: "skip", object: materialized ? "materialized view" : object![1], name: name ? objectName(name) : null };
    }
    return { kind: "skip", object: null, name: null };
  }
  if (c.eat("ALTER", "TABLE")) return alterTable(c, text);
  if (c.eat("DROP", "TABLE")) {
    c.eat("IF", "EXISTS");
    const names = splitTop(c.rest()).flatMap((part) => new Cursor(part).name() ?? []);
    return { kind: "drop", names };
  }
  if (c.eat("ALTER", "TYPE")) {
    const name = c.name();
    if (name && c.eat("ADD", "VALUE")) {
      c.eat("IF", "NOT", "EXISTS");
      const v = c.peek();
      if (v?.kind === "string") return { kind: "enum-value", name, value: v.value };
    }
    return { kind: "skip", object: null, name: null };
  }
  if (c.eat("COMMENT", "ON")) return commentOn(c);
  if (c.word("EXEC") || c.word("EXECUTE")) return extendedProperty(c);
  return { kind: "skip", object: null, name: null };
}

function createTable(c: Cursor, text: string): SqlStatement {
  c.eat("IF", "NOT", "EXISTS");
  const name = c.name();
  if (!name) return { kind: "unreadable", what: "skipped a CREATE TABLE without a table name" };
  // A partition holds rows of its parent table; the parent is the one to draw
  if (c.word("PARTITION") && c.word("OF", 1)) return { kind: "skip", object: null, name: null };
  const body = c.group();
  if (!body) return { kind: "unreadable", what: `skipped table \`${objectName(name)}\`: it has no column list (CREATE TABLE ... AS or LIKE)` };

  const table: SqlTable = { name, columns: [], constraints: [], comment: null, unreadable: [] };
  for (const element of splitTop(body)) {
    const e = new Cursor(element);
    if (atConstraint(e)) {
      const constraint = tableConstraint(e, text);
      if (constraint) table.constraints.push({ constraint, line: element[0].line, col: element[0].col });
    } else if (e.isName() && !e.word("LIKE") && !(e.word("PERIOD") && e.word("FOR", 1))) table.columns.push(column(e));
    else table.unreadable.push({ text: snippet(text, element), line: element[0].line, col: element[0].col });
  }
  // Table options: MySQL's `COMMENT='...'` is the one a diagram shows
  const rest = c.rest();
  for (let k = 0; k < rest.length; k++) {
    if (rest[k].kind !== "word" || rest[k].upper !== "COMMENT") continue;
    const v = rest[k + 1]?.kind === "punct" && rest[k + 1].value === "=" ? rest[k + 2] : rest[k + 1];
    if (v?.kind === "string") table.comment = v.value;
  }
  return { kind: "table", table };
}

function createIndex(c: Cursor, text: string, unique: boolean): SqlStatement {
  c.eat("CONCURRENTLY");
  c.eat("IF", "NOT", "EXISTS");
  let name: string | null = null;
  if (!c.word("ON") && !c.word("USING")) {
    const n = c.name();
    name = n ? objectName(n) : null;
  }
  if (c.eat("USING")) c.next(); // MySQL: CREATE INDEX ix USING BTREE ON t (...)
  if (!c.eat("ON")) return { kind: "skip", object: null, name: null };
  c.eat("ONLY");
  const table = c.name();
  if (!table) return { kind: "skip", object: null, name: null };
  if (c.eat("USING")) c.next(); // PostgreSQL: ON t USING btree (...)
  const items = indexItems(c.group() ?? [], text);
  // WHERE makes a partial index; it runs to the next clause that is not part of the condition
  const rest = c.rest();
  const at = rest.findIndex((t) => t.kind === "word" && t.upper === "WHERE");
  let where: string | null = null;
  if (at >= 0) {
    let end = rest.length;
    let depth = 0;
    for (let k = at + 1; k < rest.length; k++) {
      const t = rest[k];
      if (t.kind === "punct" && t.value === "(") depth++;
      else if (t.kind === "punct" && t.value === ")") depth--;
      else if (depth === 0 && t.kind === "word" && (t.upper === "WITH" || t.upper === "TABLESPACE" || t.upper === "ON")) {
        end = k;
        break;
      }
    }
    where = snippet(text, rest.slice(at, end));
  }
  return { kind: "index", table, index: { kind: "index", name, unique, items, where } };
}

function alterTable(c: Cursor, text: string): SqlStatement {
  c.eat("ONLY");
  c.eat("IF", "EXISTS");
  c.eat("ONLY");
  const table = c.name();
  if (!table) return { kind: "skip", object: null, name: null };
  const actions: AlterAction[] = [];
  // SQL Server lists several additions under one ADD: `ADD a int, b int`
  let adding = false;
  for (const part of splitTop(c.rest())) {
    const a = new Cursor(part);
    if (a.eat("WITH", "CHECK") || a.eat("WITH", "NOCHECK")) {
      /* SQL Server: whether existing rows are checked */
    }
    const add = a.eat("ADD");
    if (add || (adding && a.isName() && !a.word("ALTER") && !a.word("DROP"))) {
      adding = true;
      if (atConstraint(a)) {
        const constraint = tableConstraint(a, text);
        if (constraint) actions.push({ kind: "constraint", constraint, line: part[0].line, col: part[0].col });
      } else {
        a.eat("COLUMN");
        a.eat("IF", "NOT", "EXISTS");
        if (a.isName()) actions.push({ kind: "column", column: column(a) });
      }
      continue;
    }
    adding = false;
    if (a.eat("ALTER")) {
      a.eat("COLUMN");
      const col = a.isName() ? a.next().value : null;
      if (col && a.eat("SET", "NOT", "NULL")) actions.push({ kind: "null", column: col, notNull: true });
      else if (col && a.eat("DROP", "NOT", "NULL")) actions.push({ kind: "null", column: col, notNull: false });
    } else if (a.eat("MODIFY")) {
      // MySQL: MODIFY [COLUMN] c type ... redefines the column
      a.eat("COLUMN");
      if (a.isName()) actions.push({ kind: "column", column: column(a) });
    }
  }
  return { kind: "alter", table, actions };
}

function commentOn(c: Cursor): SqlStatement {
  const on = c.eat("TABLE") ? "table" : c.eat("COLUMN") ? "column" : null;
  const name = on ? c.name() : null;
  if (!on || !name || !c.eat("IS")) return { kind: "skip", object: null, name: null };
  const v = c.peek();
  return { kind: "comment", on, name, text: v?.kind === "string" ? v.value : null };
}

/** SQL Server keeps descriptions as extended properties named MS_Description:
 *  `EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'...', @level0type = N'SCHEMA',
 *  @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'users'[, @level2type = N'COLUMN', @level2name = N'email']` */
function extendedProperty(c: Cursor): SqlStatement {
  const skip: SqlStatement = { kind: "skip", object: null, name: null };
  c.next();
  const proc = c.name();
  if (!proc || objectName(proc).toLowerCase() !== "sp_addextendedproperty") return skip;
  const ORDER = ["@name", "@value", "@level0type", "@level0name", "@level1type", "@level1name", "@level2type", "@level2name"];
  const args = new Map<string, string>();
  splitTop(c.rest()).forEach((part, k) => {
    const named = part.length >= 3 && part[0].kind === "word" && part[1].kind === "punct" && part[1].value === "=";
    const value = named ? part[2] : part[0];
    const key = named ? part[0].value.toLowerCase() : ORDER[k];
    if (key && value) args.set(key, value.value);
  });
  const is = (key: string, v: string) => args.get(key)?.toUpperCase() === v;
  if (!is("@name", "MS_DESCRIPTION") || !is("@level1type", "TABLE") || !args.has("@level1name")) return skip;
  const at = { line: c.tokens[0].line, col: c.tokens[0].col };
  const schema = args.get("@level0name");
  const parts = [...(schema ? [schema] : []), args.get("@level1name")!];
  if (is("@level2type", "COLUMN") && args.has("@level2name"))
    return { kind: "comment", on: "column", name: { parts: [...parts, args.get("@level2name")!], ...at }, text: args.get("@value") ?? null };
  if (args.has("@level2type")) return skip;
  return { kind: "comment", on: "table", name: { parts, ...at }, text: args.get("@value") ?? null };
}

// ---- table elements ----

/** Is this element a table constraint rather than a column? Keywords are not reserved in every
 *  dialect, so a column may well be called `key`, `index` or `unique`: what follows decides.
 *  `KEY ix (a)` names a column inside the parentheses; `key varchar(32)` has a number there */
function atConstraint(e: Cursor): boolean {
  const t = e.peek();
  if (!t || t.kind !== "word") return false;
  const listFollows = (k: number) => e.punct("(", k) && (e.isName(k + 1) || e.punct("(", k + 1));
  switch (t.upper) {
    case "CONSTRAINT":
      return e.isName(1) && ["PRIMARY", "UNIQUE", "FOREIGN", "CHECK", "EXCLUDE", "DEFAULT"].some((w) => e.word(w, 2));
    case "PRIMARY":
    case "FOREIGN":
      return e.word("KEY", 1);
    case "CHECK":
      return e.punct("(", 1);
    case "EXCLUDE":
      return e.word("USING", 1) || e.punct("(", 1);
    case "FULLTEXT":
    case "SPATIAL":
      return e.word("KEY", 1) || e.word("INDEX", 1) || (e.isName(1) && listFollows(2));
    case "UNIQUE":
    case "KEY":
    case "INDEX":
      if (e.punct("(", 1)) return true;
      if (t.upper === "UNIQUE" && ["KEY", "INDEX", "CLUSTERED", "NONCLUSTERED", "USING"].some((w) => e.word(w, 1))) return true;
      return e.isName(1) && (listFollows(2) || ["USING", "CLUSTERED", "NONCLUSTERED"].some((w) => e.word(w, 2)));
    default:
      return false;
  }
}

/** A table constraint, or null for one that says nothing a diagram shows (CHECK, EXCLUDE, DEFAULT) */
function tableConstraint(e: Cursor, text: string): SqlConstraint | null {
  let name: string | null = null;
  if (e.eat("CONSTRAINT")) name = e.isName() ? e.next().value : null;
  if (e.eat("PRIMARY", "KEY")) {
    e.eatAny("CLUSTERED", "NONCLUSTERED");
    if (e.eat("USING")) e.next();
    return { kind: "pk", columns: columnsOf(indexItems(e.group() ?? [], text)) };
  }
  if (e.eat("FOREIGN", "KEY")) {
    if (e.isName()) e.next(); // MySQL allows an index name here
    const columns = columnsOf(indexItems(e.group() ?? [], text));
    if (!e.eat("REFERENCES")) return null;
    const ref = reference(e);
    return ref ? { kind: "fk", columns, ref } : null;
  }
  if (e.eat("CHECK")) {
    const found = valueList(e.group() ?? []);
    return found ? { kind: "check", column: found.column, values: found.values } : null;
  }
  const unique = e.eat("UNIQUE");
  e.eatAny("FULLTEXT", "SPATIAL");
  if (unique || e.word("KEY") || e.word("INDEX")) {
    e.eat("KEY") || e.eat("INDEX");
    e.eatAny("CLUSTERED", "NONCLUSTERED");
    let indexName: string | null = null;
    if (e.isName() && !e.word("USING")) indexName = e.next().value;
    e.eatAny("CLUSTERED", "NONCLUSTERED");
    if (e.eat("USING")) e.next();
    return { kind: "index", name: name ?? indexName, unique, items: indexItems(e.group() ?? [], text), where: null };
  }
  return null;
}

export const columnsOf = (items: IndexItem[]): string[] => items.flatMap((i) => ("column" in i ? [i.column] : []));

/** The items of an index or key column list. `a`, `a DESC`, `a(10)` (a MySQL prefix), `a text_pattern_ops`
 *  and `a COLLATE x` are columns; anything else (`lower(a)`, `(a + b)`) is an expression */
function indexItems(group: SqlToken[], text: string): IndexItem[] {
  return splitTop(group).map((item) => {
    const [first, ...rest] = item;
    let k = 0;
    if (rest[0]?.kind === "punct" && rest[0].value === "(" && rest[1]?.kind === "number" && rest[2]?.kind === "punct" && rest[2].value === ")") k = 3;
    const plain = rest.slice(k).every((t) => t.kind === "word" || t.kind === "quoted");
    return (first.kind === "word" || first.kind === "quoted") && plain ? { column: first.value } : { expression: snippet(text, item) };
  });
}

/** `REFERENCES t [(c, ...)]` and the clauses after it, which are consumed whole so that the NULL in
 *  `ON DELETE SET NULL` is not read as the column's nullability */
function reference(e: Cursor): SqlRef | null {
  const table = e.name();
  if (!table) return null;
  const group = e.group();
  const columns = group ? splitTop(group).map((part) => part[0].value) : null;
  for (;;) {
    if (e.eat("ON")) {
      e.next(); // DELETE | UPDATE
      if (e.eat("SET")) e.next(); // NULL | DEFAULT
      else if (e.eat("NO")) e.next(); // ACTION
      else e.next(); // CASCADE | RESTRICT
      e.skipGroup(); // PostgreSQL 15: SET NULL (a, b)
    } else if (e.eat("MATCH") || e.eat("INITIALLY")) e.next();
    else if (!(e.eat("NOT", "DEFERRABLE") || e.eat("DEFERRABLE") || e.eat("NOT", "FOR", "REPLICATION") || e.eat("ENABLE") || e.eat("DISABLE") || e.eat("VALIDATE") || e.eat("NOVALIDATE")))
      break;
  }
  return { table, columns };
}

/** Words that start a column constraint, so a column whose type is left out (SQLite) is recognized */
const CONSTRAINT_WORDS = new Set([
  "CONSTRAINT", "NOT", "NULL", "PRIMARY", "UNIQUE", "REFERENCES", "DEFAULT", "CHECK", "COLLATE",
  "GENERATED", "AUTOINCREMENT", "AUTO_INCREMENT", "IDENTITY", "COMMENT", "AS", "KEY",
]);

function column(e: Cursor): SqlColumn {
  const name = e.next();
  const col: SqlColumn = {
    name: name.value,
    type: { name: "any", args: null, values: null },
    notNull: false,
    pk: false,
    unique: null,
    ref: null,
    checkValues: null,
    comment: null,
    line: name.line,
    col: name.col,
  };
  const t = e.peek();
  if (t && (t.kind === "quoted" || (t.kind === "word" && !CONSTRAINT_WORDS.has(t.upper)))) col.type = type(e);

  let constraintName: string | null = null;
  while (!e.done) {
    const w = e.peek()!;
    if (w.kind !== "word") {
      if (e.punct("(")) e.skipGroup();
      else e.next();
      continue;
    }
    switch (w.upper) {
      case "CONSTRAINT":
        e.next();
        constraintName = e.isName() ? e.next().value : null;
        continue;
      case "NOT":
        e.next();
        if (e.eat("NULL")) col.notNull = true;
        continue;
      case "NULL":
        e.next();
        col.notNull = false;
        continue;
      case "PRIMARY":
        e.next();
        e.eat("KEY");
        col.pk = true;
        continue;
      case "KEY": // MySQL: a bare KEY on a column is its primary key
        e.next();
        col.pk = true;
        continue;
      case "UNIQUE":
        e.next();
        e.eat("KEY") || e.eat("INDEX");
        col.unique = { name: constraintName };
        continue;
      case "REFERENCES":
        e.next();
        col.ref = reference(e);
        continue;
      case "DEFAULT":
        e.next();
        expression(e);
        continue;
      case "CHECK": {
        e.next();
        const found = valueList(e.group() ?? []);
        if (found && found.column.toLowerCase() === col.name.toLowerCase()) col.checkValues = found.values;
        continue;
      }
      case "COMMENT": {
        e.next();
        if (e.punct("=")) e.next();
        const v = e.peek();
        // MySQL also accepts a double-quoted comment, which the lexer reads as a quoted name
        if (v?.kind === "string" || v?.kind === "quoted") col.comment = e.next().value;
        continue;
      }
      case "GENERATED":
        e.next();
        e.eat("ALWAYS") || e.eat("BY", "DEFAULT");
        e.eat("ON", "NULL");
        e.eat("AS");
        e.eat("IDENTITY");
        e.skipGroup();
        e.eatAny("STORED", "VIRTUAL");
        continue;
      case "AS": // a computed column: AS (expr) [STORED | VIRTUAL | PERSISTED]
        e.next();
        e.skipGroup();
        e.eatAny("STORED", "VIRTUAL", "PERSISTED");
        continue;
      case "ON": // MySQL ON UPDATE CURRENT_TIMESTAMP, SQLite ON CONFLICT REPLACE
        e.next();
        e.next();
        expression(e);
        continue;
      case "CHARACTER":
        e.next();
        if (e.eat("SET")) e.next();
        continue;
      case "COLLATE":
      case "CHARSET":
      case "STORAGE":
      case "COLUMN_FORMAT":
      case "ENCODE":
        e.next();
        e.next();
        continue;
      default:
        // AUTO_INCREMENT, IDENTITY(1,1), UNSIGNED, ENABLE, SPARSE, ...: nothing a diagram shows
        e.next();
    }
  }
  if (col.pk) col.notNull = true;
  return col;
}

const SERIAL: Record<string, string> = {
  smallserial: "smallint",
  serial2: "smallint",
  serial: "integer",
  serial4: "integer",
  bigserial: "bigint",
  serial8: "bigint",
};
/** MySQL's integer display widths (`int(11)`) do not change the type */
const INTEGERS = new Set(["tinyint", "smallint", "mediumint", "int", "integer", "bigint"]);
const INTERVAL_FIELDS = new Set(["YEAR", "MONTH", "DAY", "HOUR", "MINUTE", "SECOND", "TO"]);

/** A type, possibly several words long, normalized to what resin can write: one identifier with
 *  number arguments */
function type(e: Cursor): SqlType {
  let name = e.next().value.toLowerCase();
  while (e.punct(".") && e.isName(1)) {
    e.next();
    name = e.next().value.toLowerCase(); // public.order_status → order_status
  }
  if (name === "double") e.eat("PRECISION");
  else if ((name === "character" || name === "char") && e.eat("VARYING")) name = "varchar";
  else if (name === "national" && (e.eat("CHARACTER") || e.eat("CHAR"))) name = e.eat("VARYING") ? "nvarchar" : "nchar";
  else if (name === "nchar" && e.eat("VARYING")) name = "nvarchar";
  else if (name === "bit" && e.eat("VARYING")) name = "varbit";
  else if (name === "long" && (e.word("RAW") || e.word("VARCHAR") || e.word("VARBINARY"))) name = `long_${e.next().value.toLowerCase()}`;

  let args: number[] | null = null;
  let values: string[] | null = null;
  const group = e.group();
  if (group) {
    // MySQL also accepts enum("a", "b"), which the lexer reads as quoted names
    const strs = group.filter((t) => t.kind === "string" || (t.kind === "quoted" && (name === "enum" || name === "set")));
    if (strs.length) values = strs.map((t) => t.value);
    // varchar(max) and number(*,0) leave the length open
    else if (!group.some((t) => (t.kind === "word" && t.upper === "MAX") || (t.kind === "punct" && t.value === "*")))
      args = group.filter((t) => t.kind === "number" && /^\d+$/.test(t.value)).map((t) => Number(t.value));
    if (args?.length === 0) args = null;
  }
  if (name === "timestamp" || name === "time") {
    if (e.eat("WITH", "TIME", "ZONE")) name += "tz";
    else if (e.eat("WITH", "LOCAL", "TIME", "ZONE")) name += "ltz";
    else e.eat("WITHOUT", "TIME", "ZONE");
  }
  if (name === "interval")
    while (e.peek()?.kind === "word" && INTERVAL_FIELDS.has(e.peek()!.upper)) {
      e.next();
      e.skipGroup();
    }
  let array = false;
  while (e.punct("[")) {
    while (!e.done && !e.punct("]")) e.next();
    e.next();
    array = true;
  }
  if (e.eat("ARRAY")) array = true;
  e.eatAny("UNSIGNED", "SIGNED", "ZEROFILL");

  name = SERIAL[name] ?? name;
  if (INTEGERS.has(name)) args = null;
  name = name.replace(/[^a-z0-9_]/g, "_");
  if (!/^[a-z_]/.test(name)) name = `_${name}`;
  // PostgreSQL's own name for an array type: text[] is _text
  if (array) name = `_${name}`;
  return { name, args, values };
}

/** Skip a DEFAULT or ON UPDATE value: one term, then casts and operators that continue it. Words
 *  after it (NOT NULL, COMMENT ...) are left for the column */
function expression(e: Cursor): void {
  const term = (): void => {
    const t = e.peek();
    if (!t) return;
    if (t.kind === "punct") {
      if (t.value === "(") e.skipGroup();
      else if (t.value === "-" || t.value === "+") {
        e.next();
        term();
      }
      return;
    }
    e.next();
    if (t.kind === "word" && e.punct("(")) e.skipGroup(); // a function call: now(), nextval('seq')
  };
  term();
  for (;;) {
    if (e.punct("::")) {
      e.next();
      if (e.isName()) type(e);
    } else if (["+", "-", "*", "/", "|", "%"].some((p) => e.punct(p))) {
      e.next();
      if (e.punct("|")) e.next();
      term();
    } else return;
  }
}

/** The values of a check that lists them, in the forms dialects write:
 *  `status IN ('A', 'B')`, PostgreSQL's `(status)::text = ANY (ARRAY['A'::text, 'B'::text])` and
 *  SQL Server's `[status]='A' OR [status]='B'`. null for any other check */
function valueList(group: readonly SqlToken[]): { column: string; values: string[] } | null {
  // Drop parentheses and casts (with their type arguments): what is left is a flat sequence
  const flat: SqlToken[] = [];
  for (let k = 0; k < group.length; k++) {
    const t = group[k];
    if (t.kind === "punct" && (t.value === "(" || t.value === ")")) continue;
    if (t.kind === "punct" && t.value === "::") {
      while (group[k + 1] && (group[k + 1].kind === "word" || group[k + 1].kind === "quoted" || (group[k + 1].kind === "punct" && group[k + 1].value === "."))) k++;
      if (group[k + 1]?.kind === "punct" && group[k + 1].value === "(") {
        while (group[k + 1] && !(group[k + 1].kind === "punct" && group[k + 1].value === ")")) k++;
        k++;
      }
      // An array cast, text[]: only an empty pair, so the ] that closes ARRAY[...] stays
      while (group[k + 1]?.kind === "punct" && group[k + 1].value === "[" && group[k + 2]?.kind === "punct" && group[k + 2].value === "]") k += 2;
      continue;
    }
    flat.push(t);
  }
  const isValue = (t: SqlToken | undefined) => t !== undefined && (t.kind === "string" || t.kind === "number");
  const isWord = (t: SqlToken | undefined, w: string) => t !== undefined && t.kind === "word" && t.upper === w;
  const isPunct = (t: SqlToken | undefined, p: string) => t !== undefined && t.kind === "punct" && t.value === p;
  const head = flat[0];
  if (!head || (head.kind !== "word" && head.kind !== "quoted")) return null;

  /** Values separated by commas from k to the end, or null */
  const list = (k: number, end = flat.length): string[] | null => {
    const values: string[] = [];
    for (; k < end; k += 2) {
      if (!isValue(flat[k]) || (k + 1 < end && !isPunct(flat[k + 1], ","))) return null;
      values.push(flat[k].value);
    }
    return values.length ? values : null;
  };
  if (isWord(flat[1], "IN")) {
    const values = list(2);
    return values ? { column: head.value, values } : null;
  }
  if (isPunct(flat[1], "=") && isWord(flat[2], "ANY") && isWord(flat[3], "ARRAY") && isPunct(flat[4], "[") && isPunct(flat[flat.length - 1], "]")) {
    const values = list(5, flat.length - 1);
    return values ? { column: head.value, values } : null;
  }
  // a = 'x' OR a = 'y' ...
  const values: string[] = [];
  for (let k = 0; k < flat.length; k += 4) {
    const col = flat[k];
    if (!col || col.value !== head.value || !isPunct(flat[k + 1], "=") || !isValue(flat[k + 2])) return null;
    values.push(flat[k + 2].value);
    if (k + 3 < flat.length && !isWord(flat[k + 3], "OR")) return null;
  }
  return values.length > 1 ? { column: head.value, values } : null;
}

const strings = (group: readonly SqlToken[]): string[] => group.filter((t) => t.kind === "string").map((t) => t.value);
